name: My first pipeline
run-name: Mon premier run
on:
  push:
    branches:
      - main
jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world echo
        run: echo "Hellow The real world !"
      - name: install nodejs
        run: |
          sudo apt-get update
          sudo apt-get install nodejs
          sudo apt-get install npm
      - name: ls my projet
        run: ls